spring.application.name=tesis2025
spring.datasource.url=jdbc:postgresql://ep-autumn-darkness-ac7krcu9-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_p82MPkBjQxqE

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

